In [ ]:
# Importing the libraries
from sklearn.metrics import mean_absolute_error as mae
from sklearn.metrics import mean_squared_error as mse
import pandas as pd
import numpy as np
import random as rd
import re
import math
import string

In [ ]:
# Importing the dataset
dataset = pd.read_csv('https://personal.utdallas.edu/~rxr210009/cnnhealth.txt', header=None, sep='\n')

In [ ]:
dataset

                                                      0
0     576880531301801984|Sat Mar 14 23:00:11 +0000 2...
1     576820122666471424|Sat Mar 14 19:00:08 +0000 2...
2     576744652717461504|Sat Mar 14 14:00:15 +0000 2...
3     576736754436304896|Sat Mar 14 13:28:52 +0000 2...
4     576736614766010368|Sat Mar 14 13:28:18 +0000 2...
...                                                 ...
4056  239699936671854593|Sun Aug 26 12:24:52 +0000 2...
4057  239504620710420480|Sat Aug 25 23:28:46 +0000 2...
4058  239410205757145088|Sat Aug 25 17:13:35 +0000 2...
4059  239386320416428032|Sat Aug 25 15:38:41 +0000 2...
4060  239366825018806272|Sat Aug 25 14:21:12 +0000 2...

[4061 rows x 1 columns]

# Pre-processing the dataset

In [ ]:
df = dataset[0].str.split('|', expand=True)

In [ ]:
display(df)

,0,1,2,3,4
0,576880531301801984,Sat Mar 14 23:00:11 +0000 2015,An abundance of online info can turn us into e...,None,None
1,576820122666471424,Sat Mar 14 19:00:08 +0000 2015,A plant-based diet that incorporates fish may ...,None,None
2,576744652717461504,Sat Mar 14 14:00:15 +0000 2015,It doesn't take much to damage your hearing at...,None,None
3,576736754436304896,Sat Mar 14 13:28:52 +0000 2015,RT @CNN: Forever young? Discover this islandâ€™s...,None,None
4,576736614766010368,Sat Mar 14 13:28:18 +0000 2015,RT @CNN: Is post-traumatic stress disorder in ...,None,None
...,...,...,...,...,...
4056,239699936671854593,Sun Aug 26 12:24:52 +0000 2012,RT @EverydayHealth: Want killer abs? @JillianM...,None,None
4057,239504620710420480,Sat Aug 25 23:28:46 +0000 2012,Medicare at stake -- @sanjayguptaCNN talks abo...,None,None
4058,239410205757145088,Sat Aug 25 17:13:35 +0000 2012,Ann Romney talks about her experience with MS ...,None,None
4059,239386320416428032,Sat Aug 25 15:38:41 +0000 2012,Make sure your first marathon isn't your last!...,None,None
4060,239366825018806272,Sat Aug 25 14:21:12 +0000 2012,Robin Roberts' cancer diagnosis http://at.cnn....,None,None

In [ ]:
df = df.drop([0,1,3, 4], axis=1)

In [ ]:
df['clean_text']=df[2].str.replace('(\@\w+.*?)',"")

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.

In [ ]:
display(df)

,2,clean_text
0,An abundance of online info can turn us into e...,An abundance of online info can turn us into e...
1,A plant-based diet that incorporates fish may ...,A plant-based diet that incorporates fish may ...
2,It doesn't take much to damage your hearing at...,It doesn't take much to damage your hearing at...
3,RT @CNN: Forever young? Discover this islandâ€™s...,RT : Forever young? Discover this islandâ€™s sec...
4,RT @CNN: Is post-traumatic stress disorder in ...,RT : Is post-traumatic stress disorder in your...
...,...,...
4056,RT @EverydayHealth: Want killer abs? @JillianM...,RT : Want killer abs? shows you how get them:...
4057,Medicare at stake -- @sanjayguptaCNN talks abo...,Medicare at stake -- talks about politicians'...
4058,Ann Romney talks about her experience with MS ...,Ann Romney talks about her experience with MS ...
4059,Make sure your first marathon isn't your last!...,Make sure your first marathon isn't your last!...
4060,Robin Roberts' cancer diagnosis http://at.cnn....,Robin Roberts' cancer diagnosis http://at.cnn....

In [ ]:
import re
df['cleanLinks'] = df['clean_text'].apply(lambda x: re.split('http:\/\/.*', str(x))[0])

In [ ]:
display(df)

,2,clean_text,cleanLinks
0,An abundance of online info can turn us into e...,An abundance of online info can turn us into e...,An abundance of online info can turn us into e...
1,A plant-based diet that incorporates fish may ...,A plant-based diet that incorporates fish may ...,A plant-based diet that incorporates fish may ...
2,It doesn't take much to damage your hearing at...,It doesn't take much to damage your hearing at...,It doesn't take much to damage your hearing at...
3,RT @CNN: Forever young? Discover this islandâ€™s...,RT : Forever young? Discover this islandâ€™s sec...,RT : Forever young? Discover this islandâ€™s sec...
4,RT @CNN: Is post-traumatic stress disorder in ...,RT : Is post-traumatic stress disorder in your...,RT : Is post-traumatic stress disorder in your...
...,...,...,...
4056,RT @EverydayHealth: Want killer abs? @JillianM...,RT : Want killer abs? shows you how get them:...,RT : Want killer abs? shows you how get them:
4057,Medicare at stake -- @sanjayguptaCNN talks abo...,Medicare at stake -- talks about politicians'...,Medicare at stake -- talks about politicians'...
4058,Ann Romney talks about her experience with MS ...,Ann Romney talks about her experience with MS ...,Ann Romney talks about her experience with MS
4059,Make sure your first marathon isn't your last!...,Make sure your first marathon isn't your last!...,Make sure your first marathon isn't your last!
4060,Robin Roberts' cancer diagnosis http://at.cnn....,Robin Roberts' cancer diagnosis http://at.cnn....,Robin Roberts' cancer diagnosis

In [ ]:
df['clean_tweets']=df['cleanLinks'].str.replace('#',"")

In [ ]:
df['preprocessed_clean_text']=df['clean_tweets'].str.replace('RT :',"")

In [ ]:
display(df)

,2,clean_text,cleanLinks,clean_tweets,preprocessed_clean_text
0,An abundance of online info can turn us into e...,An abundance of online info can turn us into e...,An abundance of online info can turn us into e...,An abundance of online info can turn us into e...,An abundance of online info can turn us into e...
1,A plant-based diet that incorporates fish may ...,A plant-based diet that incorporates fish may ...,A plant-based diet that incorporates fish may ...,A plant-based diet that incorporates fish may ...,A plant-based diet that incorporates fish may ...
2,It doesn't take much to damage your hearing at...,It doesn't take much to damage your hearing at...,It doesn't take much to damage your hearing at...,It doesn't take much to damage your hearing at...,It doesn't take much to damage your hearing at...
3,RT @CNN: Forever young? Discover this islandâ€™s...,RT : Forever young? Discover this islandâ€™s sec...,RT : Forever young? Discover this islandâ€™s sec...,RT : Forever young? Discover this islandâ€™s sec...,Forever young? Discover this islandâ€™s secrets...
4,RT @CNN: Is post-traumatic stress disorder in ...,RT : Is post-traumatic stress disorder in your...,RT : Is post-traumatic stress disorder in your...,RT : Is post-traumatic stress disorder in your...,Is post-traumatic stress disorder in your gen...
...,...,...,...,...,...
4056,RT @EverydayHealth: Want killer abs? @JillianM...,RT : Want killer abs? shows you how get them:...,RT : Want killer abs? shows you how get them:,RT : Want killer abs? shows you how get them:,Want killer abs? shows you how get them:
4057,Medicare at stake -- @sanjayguptaCNN talks abo...,Medicare at stake -- talks about politicians'...,Medicare at stake -- talks about politicians'...,Medicare at stake -- talks about politicians'...,Medicare at stake -- talks about politicians'...
4058,Ann Romney talks about her experience with MS ...,Ann Romney talks about her experience with MS ...,Ann Romney talks about her experience with MS,Ann Romney talks about her experience with MS,Ann Romney talks about her experience with MS
4059,Make sure your first marathon isn't your last!...,Make sure your first marathon isn't your last!...,Make sure your first marathon isn't your last!,Make sure your first marathon isn't your last!,Make sure your first marathon isn't your last!
4060,Robin Roberts' cancer diagnosis http://at.cnn....,Robin Roberts' cancer diagnosis http://at.cnn....,Robin Roberts' cancer diagnosis,Robin Roberts' cancer diagnosis,Robin Roberts' cancer diagnosis

# Applying K-means clustering to the processed input data

In [ ]:

class K_Means_lib:
  def __init__(self, tweets_lists):
    self.list_of_twitter_tweets = tweets_lists
  
  def k_means(self, k=3, max_iterations=30):

    list_of_centroids = []    
    iter_count = 0
    prev_list_of_centroids = []
    count = 0
    hash_map = dict()
    while count < k:
        random_tweet_idx = rd.randint(0, len(self.list_of_twitter_tweets) - 1)
        if random_tweet_idx not in hash_map:
            count += 1
            hash_map[random_tweet_idx] = True
            list_of_centroids.append(self.list_of_twitter_tweets[random_tweet_idx])

    while (self.has_converged(prev_list_of_centroids, list_of_centroids)) == False and (iter_count < max_iterations):

        #print("running iteration " + str(iter_count))
        cluster_components = self.cluster_assignment(self.list_of_twitter_tweets, list_of_centroids)
        prev_list_of_centroids = list_of_centroids
        list_of_centroids = self.reassign_centroid(cluster_components)
        iter_count = iter_count + 1

    
    sq_sum_err = self.compute_sq_sum_err(cluster_components)

    return cluster_components, sq_sum_err


  def has_converged(self, prev_centroid, new_centroids):

      if len(prev_centroid) != len(new_centroids):
          return False

      for c in range(len(new_centroids)):
          if " ".join(new_centroids[c]) != " ".join(prev_centroid[c]):
              return False

      return True


  def cluster_assignment(self, tweets, centroids):

      clusters = dict()

      for t in range(len(tweets)):
          min_dis = math.inf
          cluster_idx = -1;
          for c in range(len(centroids)):
              dis = self.get_jaccard_dist(centroids[c], tweets[t])
              if centroids[c] == tweets[t]:
                  # print("tweet and centroid are equal with c: " + str(c) + ", t" + str(t))
                  cluster_idx = c
                  min_dis = 0
                  break

              if dis < min_dis:
                  cluster_idx = c
                  min_dis = dis

          if min_dis == 1:
              cluster_idx = rd.randint(0, len(centroids) - 1)

          clusters.setdefault(cluster_idx, []).append([tweets[t]])
          last_tweet_idx = len(clusters.setdefault(cluster_idx, [])) - 1
          clusters.setdefault(cluster_idx, [])[last_tweet_idx].append(min_dis)

      return clusters


  def reassign_centroid(self, cluster_components):

      list_of_centroids = []

      for c in range(len(cluster_components)):
          min_dis_sum = math.inf
          index_of_centroid = -1
          min_dis_dp = []

          for t1 in range(len(cluster_components[c])):
              min_dis_dp.append([])
              dis_sum = 0
              for t2 in range(len(cluster_components[c])):
                  if t1 != t2:
                      if t2 < t1:
                          dis = min_dis_dp[t2][t1]
                      else:
                          dis = self.get_jaccard_dist(cluster_components[c][t1][0], cluster_components[c][t2][0])

                      min_dis_dp[t1].append(dis)
                      dis_sum += dis
                  else:
                      min_dis_dp[t1].append(0)

              if dis_sum < min_dis_sum:
                  min_dis_sum = dis_sum
                  index_of_centroid = t1

          list_of_centroids.append(cluster_components[c][index_of_centroid][0])

      return list_of_centroids


  def get_jaccard_dist(self, tweet_x, tweet_y):

      union = set().union(tweet_x, tweet_y)
      intersect = set(tweet_x).intersection(tweet_y)

      return 1 - (len(intersect) / len(union))


  def compute_sq_sum_err(self, cluster_components):

      sq_sum_err = 0
      for cluster in range(len(cluster_components)):
          for t in range(len(cluster_components[cluster])):
              sq_sum_err = sq_sum_err + (cluster_components[cluster][t][1] * cluster_components[cluster][t][1])

      return sq_sum_err

In [ ]:
def get_cluster_size(clusters):
  ans_str = ''
  for z in range(0,len(list(clusters.keys()))):
    ans_str += 'Cluster '+str(z)+' : '+str(len(clusters[z]))+' tweets '
  return ans_str

In [ ]:
exp_k=[]
exp_sq_sum_errors=[]
exp_clusters=[]
for exp in range(1,6):
  clusters_computed, sq_sum_errors = K_Means_lib(df['preprocessed_clean_text'].tolist()).k_means(k=2+exp)
  exp_k.append(2+exp)
  exp_sq_sum_errors.append(sq_sum_errors)
  exp_clusters.append(get_cluster_size(clusters_computed))

results = pd.DataFrame(list(zip(exp_k, exp_sq_sum_errors, exp_clusters)), columns=['K-Values', 'Square Sum Error Values', 'Cluster Sizes'])

In [ ]:
#display results
results

,K-Values,Square Sum Error Values,Cluster Sizes
0,3,540.167756,Cluster 0 : 2271 tweets Cluster 1 : 1709 tweet...
1,4,517.198108,Cluster 0 : 1882 tweets Cluster 1 : 806 tweets...
2,5,526.955633,Cluster 0 : 1199 tweets Cluster 1 : 25 tweets ...
3,6,475.347810,Cluster 0 : 373 tweets Cluster 1 : 1125 tweets...
4,7,490.038657,Cluster 0 : 424 tweets Cluster 1 : 256 tweets ...